👷 [Cicd] deploy-dev.yml 수정

diff --git a/.github/workflows/deploy-dev.yml b/.github/workflows/deploy-dev.yml
--- a/.github/workflows/deploy-dev.yml
+++ b/.github/workflows/deploy-dev.yml
@@ -4,6 +4,9 @@ on:
     types: [ closed ]
     branches:
       - develop
+  push:
+    branches:
+      - cicd/234
   workflow_dispatch: # 수동 실행 가능
 
 jobs:
@@ -12,7 +15,7 @@ jobs:
 
     env: # 전체 job에서 사용할 환경 변수 설정
       JWT_SECRET: ${{ secrets.JWT_SECRET }}
-      RDS_PRIVATE_IP: ${{ secrets.RDS_PRIVATE_IP }}
+      DEV_DB_HOST: ${{ secrets.DEV_DB_HOST }}
       RDS_PORT: ${{ secrets.RDS_PORT }}
       DEV_DB_SCHEMA_NAME: ${{ secrets.DEV_DB_SCHEMA_NAME }}
       DB_USERNAME: ${{ secrets.DB_USERNAME }}
@@ -61,7 +64,7 @@ jobs:
           platforms: linux/amd64
           build-args: |  # Dockerfile에서 사용할 환경 변수 전달
             JWT_SECRET= ${{ secrets.JWT_SECRET }}
-            RDS_PRIVATE_IP= ${{ secrets.RDS_PRIVATE_IP }}
+            DEV_DB_HOST= ${{ secrets.DEV_DB_HOST }}
             RDS_PORT= ${{ secrets.RDS_PORT }}
             DEV_DB_SCHEMA_NAME= ${{ secrets.DEV_DB_SCHEMA_NAME }}
             DB_USERNAME= ${{ secrets.DB_USERNAME }}
@@ -75,23 +78,23 @@ jobs:
       - name: EC2에 배포
         uses: appleboy/ssh-action@v1.1.0
         with:
-          host: ${{ secrets.EC2_HOST }} # EC2 퍼블릭 IP
+          host: ${{ secrets.DEV_EC2_HOST }} # EC2 퍼블릭 IP
           username: ubuntu # EC2 사용자 (기본은 ubuntu)
-          key: ${{ secrets.EC2_SSH_KEY }} # EC2 SSH Private Key
+          key: ${{ secrets.DEV_EC2_SSH_KEY }} # EC2 SSH Private Key
           script_stop: true # SSH 명령어 실행 중 에러가 발생하면 워크플로 중단
           script: |
-            sudo fuser -k -n tcp 8081 || true
+            sudo fuser -k -n tcp 8080 || true
 
             docker rm -f gamegoo-api-v2-dev
 
             docker pull ${{ secrets.DOCKERHUB_USERNAME }}/gamegoo-api-v2-dev:${{ github.sha }}
 
             docker run -d \
-            -p 8081:8081 \
+            -p 8080:8080 \
             --name gamegoo-api-v2-dev \
             -e SPRING_PROFILES_ACTIVE=dev \
             -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
-            -e RDS_PRIVATE_IP=${{ secrets.RDS_PRIVATE_IP }} \
+            -e DEV_DB_HOST=${{ secrets.DEV_DB_HOST }} \
             -e RDS_PORT=${{ secrets.RDS_PORT }} \
             -e DEV_DB_SCHEMA_NAME=${{ secrets.DEV_DB_SCHEMA_NAME }} \
             -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
@@ -101,18 +104,14 @@ jobs:
             -e SOCKET_SERVER_URL=${{ secrets.SOCKET_SERVER_URL }} \
             ${{ secrets.DOCKERHUB_USERNAME }}/gamegoo-api-v2-dev:${{ github.sha }}
 
-      # 8. 기존 Docker 이미지 삭제
-      - name: 기존 Docker 이미지 삭제
-        run: docker image prune -a
-
       # 실패 시 디스코드에 알림 보내기
-      - name: 배포 실패 시 디스코드 알림 전송
-        if: failure() # 이전 스텝이 실패한 경우에만 실행
-        run: |
-          PR_NUMBER="${{ github.event.pull_request.number }}"
-          PR_TITLE="${{ github.event.pull_request.title }}"
-          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
-          PR_URL="${{ github.event.pull_request.html_url }}"
-          curl -X POST -H "Content-Type: application/json" \
-          -d "{\"content\": \"🚨 **Gamegoo v2 API 개발 서버 배포 실패** 🚨\nPR 번호: ${PR_NUMBER}\nPR 제목: ${PR_TITLE}\nPR 작성자: ${PR_AUTHOR}\n[PR 보기](${PR_URL})\"}" \
-          $DISCORD_WEBHOOK_URL
+#      - name: 배포 실패 시 디스코드 알림 전송
+#        if: failure() # 이전 스텝이 실패한 경우에만 실행
+#        run: |
+#          PR_NUMBER="${{ github.event.pull_request.number }}"
+#          PR_TITLE="${{ github.event.pull_request.title }}"
+#          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
+#          PR_URL="${{ github.event.pull_request.html_url }}"
+#          curl -X POST -H "Content-Type: application/json" \
+#          -d "{\"content\": \"🚨 **Gamegoo v2 API 개발 서버 배포 실패** 🚨\nPR 번호: ${PR_NUMBER}\nPR 제목: ${PR_TITLE}\nPR 작성자: ${PR_AUTHOR}\n[PR 보기](${PR_URL})\"}" \
+#          $DISCORD_WEBHOOK_URL
